import re

HERO_DISPLAY_NAMES = {
    "ana": "Ana",
    "anran": "Anran",
    "ashe": "Ashe",
    "baptiste": "Baptiste",
    "bastion": "Bastion",
    "brigitte": "Brigitte",
    "cassidy": "Cassidy",
    "dmon": "D.Mon",
    "dva": "D.Va",
    "domina": "Domina",
    "doomfist": "Doomfist",
    "echo": "Echo",
    "emre": "Emre",
    "freja": "Freja",
    "genji": "Genji",
    "hanzo": "Hanzo",
    "hazard": "Hazard",
    "illari": "Illari",
    "jetpack_cat": "Jetpack Cat",
    "junker_queen": "Junker Queen",
    "junkrat": "Junkrat",
    "juno": "Juno",
    "kiriko": "Kiriko",
    "lifeweaver": "Lifeweaver",
    "lucio": "Lúcio",
    "mauga": "Mauga",
    "mei": "Mei",
    "mercy": "Mercy",
    "mizuki": "Mizuki",
    "moira": "Moira",
    "orisa": "Orisa",
    "pharah": "Pharah",
    "ramattra": "Ramattra",
    "reaper": "Reaper",
    "reinhardt": "Reinhardt",
    "roadhog": "Roadhog",
    "shion": "Shion",
    "sierra": "Sierra",
    "sigma": "Sigma",
    "sojourn": "Sojourn",
    "soldier_76": "Soldier: 76",
    "sombra": "Sombra",
    "symmetra": "Symmetra",
    "torbjorn": "Torbjorn",
    "tracer": "Tracer",
    "vendetta": "Vendetta",
    "venture": "Venture",
    "widowmaker": "Widowmaker",
    "winston": "Winston",
    "wrecking_ball": "Wrecking Ball",
    "wuyang": "Wuyang",
    "zarya": "Zarya",
    "zenyatta": "Zenyatta",
}